apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: backend
  labels:
    app: auth-service
type: Opaque
data:
  # Base64 placeholders only (no plaintext secrets)
  MONGO_URI: "bW9uZ29kYjovL3VzZXI6cGFzc0Btb25nbzozNzAxNy9hdXRo"
  JWT_ACCESS_SECRET: "and0X2FjY2Vzc19zZWNyZXQ="
  JWT_REFRESH_SECRET: "and0X3JlZnJlc2hfc2VjcmV0"
  REDIS_URL: "cmVkaXM6Ly9yZWRpczo2Mzc5"
